import { createRequire } from "node:module";
import type { Project } from "@prisma/client";
import type { GeneratedFile } from "../types/generatedProject.js";
import type { Transform } from "node:stream";
import { createPomXml } from "../utils/createPomXml.js";

type Archive = Transform & {
  append(content: string, options: { name: string }): Archive;
  finalize(): Promise<void>;
};

type ArchiverFactory = (
  format: "zip",
  options: {
    zlib: {
      level: number;
    };
  },
) => Archive;
const require = createRequire(import.meta.url);
const archiver = require("archiver") as ArchiverFactory;

export function createProjectArchive(project: Project) {
  const sourceFiles = parseFiles(project.sourceFiles, "sourceFiles");
  const testFiles = parseFiles(project.testFiles, "testFiles");

  const archive = archiver("zip", {
    zlib: {
      level: 9,
    },
  });

  archive.append(createPomXml(), {
    name: "pom.xml",
  });

  for (const file of sourceFiles) {
    archive.append(file.content, {
      name: `src/main/java/${file.fileName}`,
    });
  }

  for (const file of testFiles) {
    archive.append(file.content, {
      name: `src/test/java/${file.fileName}`,
    });
  }

  archive.append(createReadme(project), {
    name: "README.md",
  });

  return archive;
}

function parseFiles(value: unknown, label: string): GeneratedFile[] {
  if (!Array.isArray(value)) {
    throw new Error(`${label} is not a valid file array.`);
  }

  return value.map((item) => {
    if (
      typeof item !== "object" ||
      item === null ||
      !("fileName" in item) ||
      !("content" in item) ||
      typeof item.fileName !== "string" ||
      typeof item.content !== "string"
    ) {
      throw new Error(`${label} contains an invalid file.`);
    }

    return {
      fileName: item.fileName,
      content: item.content,
    };
  });
}

function createReadme(project: Project): string {
  return `# Generated AgentForge Project

## Project Idea

${project.idea}

## Running The Tests

Make sure Java 17 and Maven are installed.

\`\`\`bash
mvn test
\`\`\`

This project was generated by AgentForge.
`;
}
